package com.alibaba.entity;

public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.pid
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.name
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.flag
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.pid
     *
     * @return the value of product_category.pid
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.pid
     *
     * @param pid the value for product_category.pid
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.name
     *
     * @return the value of product_category.name
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.name
     *
     * @param name the value for product_category.name
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.flag
     *
     * @return the value of product_category.flag
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.flag
     *
     * @param flag the value for product_category.flag
     *
     * @mbggenerated Sat Nov 02 09:15:36 CST 2019
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}